name: demand-forecast-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas>=2.0.0
    - numpy>=1.24.0
    - scikit-learn>=1.3.0
    - xgboost>=2.0.0
    - prophet>=1.1.4
    - azureml-inference-server-http
    - inference-schema
