name: Create Jira Ticket From GitHub Issue

on:
  issues:
    types: [opened]

jobs:
  create-jira-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Create Jira Issue
        run: |
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
          -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "fields": {
              "project": {
                "key": "MAI"
              },
              "summary": "${{ github.event.issue.title }}",
              "description": {
                "type": "doc",
                "version": 1,
                "content": [
                  {
                    "type": "paragraph",
                    "content": [
                      {
                        "text": "${{ github.event.issue.body }}",
                        "type": "text"
                      }
                    ]
                  }
                ]
              },
              "issuetype": {
                "name": "Story"
              }
            }
          }' \
          ${{ secrets.JIRA_BASE_URL }}/rest/api/3/issue)
      
          echo "HTTP Status: $RESPONSE"
          cat response.json
      
          if [ "$RESPONSE" -ne 201 ]; then
            echo "Jira ticket creation failed"
            exit 1
          fi
